
PawnCommon = {
	["ShowUpgradesOnTooltips"] = true,
	["AlignNumbersRight"] = false,
	["ShowBagUpgradeAdvisor"] = true,
	["ShowItemID"] = false,
	["ShowRelicUpgrades"] = false,
	["ShowValuesForUpgradesOnly"] = true,
	["ShowItemLevelUpgrades"] = true,
	["ShownGettingStarted"] = true,
	["Debug"] = false,
	["ColorTooltipBorder"] = true,
	["ShowTooltipIcons"] = true,
	["Digits"] = 1,
	["ShowSocketingAdvisor"] = true,
	["Scales"] = {
		["\"MrRobot\":HUNTER3"] = {
			["IconTexturePath"] = 461113,
			["PerCharacterOptions"] = {
			},
			["Color"] = "a9d271",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Survival",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "7e9d54",
		},
		["Restless - Arms - Patchwerk (Raidbots)"] = {
			["IconTexturePath"] = 132355,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsFrill"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 1.57,
				["Dps"] = 19.92,
				["Strength"] = 3.51,
				["HasteRating"] = 1.44,
				["MasteryRating"] = 1.81,
				["IsCrossbow"] = -1000000,
				["Versatility"] = 1.68,
				["IsBow"] = -1000000,
				["IsGun"] = -1000000,
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 1,
			["PerCharacterOptions"] = {
				["Restless-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
		},
		["\"MrRobot\":WARLOCK1"] = {
			["IconTexturePath"] = 136145,
			["PerCharacterOptions"] = {
				["Dying-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "8687ed",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Affliction",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "6465b1",
		},
		["\"MrRobot\":SHAMAN1"] = {
			["IconTexturePath"] = 136048,
			["PerCharacterOptions"] = {
				["Selognia-Frostwolf"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "006fdc",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Elemental",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "0053a5",
		},
		["\"MrRobot\":PRIEST1"] = {
			["IconTexturePath"] = 135940,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fefefe",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Discipline",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "bebebe",
		},
		["Koryx - Frost - Patchwerk (Raidbots)"] = {
			["IconTexturePath"] = 135773,
			["PerCharacterOptions"] = {
				["Koryx-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 2,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsFist"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 4.79,
				["IsStaff"] = -1000000,
				["HasteRating"] = 3.72,
				["OffHandDps"] = 8.12,
				["IsCrossbow"] = -1000000,
				["IsThrown"] = -1000000,
				["IsFrill"] = -1000000,
				["Dps"] = 18.68,
				["Strength"] = 6.37,
				["MasteryRating"] = 4.19,
				["Versatility"] = 3.43,
				["IsDagger"] = -1000000,
				["IsGun"] = -1000000,
				["IsShield"] = -1000000,
				["IsBow"] = -1000000,
			},
		},
		["\"MrRobot\":PRIEST3"] = {
			["IconTexturePath"] = 136207,
			["PerCharacterOptions"] = {
				["Lisianthia-Defias Brotherhood"] = {
					["Visible"] = true,
				},
				["Korysp-Twisting Nether"] = {
					["Visible"] = true,
				},
				["Injured-Frostwolf"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fefefe",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Shadow",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "bebebe",
		},
		["\"MrRobot\":MAGE3"] = {
			["IconTexturePath"] = 135846,
			["PerCharacterOptions"] = {
				["Selonialt-Ravencrest"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "3ec6ea",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Frost",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "2e94af",
		},
		["\"MrRobot\":MAGE2"] = {
			["IconTexturePath"] = 135810,
			["PerCharacterOptions"] = {
				["Sobriquet-Twisting Nether"] = {
					["Visible"] = true,
				},
				["Ellesandre-Defias Brotherhood"] = {
					["Visible"] = true,
				},
				["Miquella-Twisting Nether"] = {
					["Visible"] = true,
				},
				["Dayv-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "3ec6ea",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Fire",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "2e94af",
		},
		["Icewyrm - Devastation - Patchwerk (Raidbots)"] = {
			["IconTexturePath"] = 4511811,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsOffHand"] = -1000000,
				["Intellect"] = 9.65,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 6.15,
				["IsBow"] = -1000000,
				["IsPlate"] = -1000000,
				["IsPolearm"] = -1000000,
				["IsGun"] = -1000000,
				["HasteRating"] = 5.76,
				["MasteryRating"] = 5.39,
				["Versatility"] = 4.95,
				["IsCrossbow"] = -1000000,
				["IsShield"] = -1000000,
				["IsThrown"] = -1000000,
			},
			["Color"] = "33937f",
			["ClassID"] = 13,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 1,
			["PerCharacterOptions"] = {
				["Icewyrm-Frostwolf"] = {
					["Visible"] = true,
				},
			},
		},
		["\"MrRobot\":WARLOCK3"] = {
			["IconTexturePath"] = 136186,
			["PerCharacterOptions"] = {
			},
			["Color"] = "8687ed",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Destruction",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "6465b1",
		},
		["Felwinter - Arms - Patchwerk (Raidbots)"] = {
			["IconTexturePath"] = 132355,
			["PerCharacterOptions"] = {
				["Felwinter-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 1,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsFrill"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 3.68,
				["Dps"] = 32.54,
				["Strength"] = 6.28,
				["HasteRating"] = 3.5,
				["MasteryRating"] = 3.64,
				["Versatility"] = 3.62,
				["IsCrossbow"] = -1000000,
				["IsBow"] = -1000000,
				["IsGun"] = -1000000,
			},
		},
		["\"MrRobot\":ROGUE2"] = {
			["IconTexturePath"] = 236286,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fef367",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Outlaw",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "beb64d",
		},
		["Seloniaa - Feral - Patchwerk (Raidbots)"] = {
			["IconTexturePath"] = 132115,
			["PerCharacterOptions"] = {
				["Seloniaa-Ravencrest"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 2,
			["Values"] = {
				["IsOffHand"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 2.11,
				["Agility"] = 3.9,
				["HasteRating"] = 1.62,
				["MasteryRating"] = 1.71,
				["Versatility"] = 1.82,
				["IsPlate"] = -1000000,
				["IsGun"] = -1000000,
				["IsFrill"] = -1000000,
				["Is2HAxe"] = -1000000,
				["IsThrown"] = -1000000,
				["Dps"] = 21.46,
				["IsMail"] = -1000000,
				["IsSword"] = -1000000,
				["IsWand"] = -1000000,
				["IsBow"] = -1000000,
				["IsCrossbow"] = -1000000,
				["Is2HSword"] = -1000000,
				["IsAxe"] = -1000000,
				["IsShield"] = -1000000,
			},
		},
		["\"MrRobot\":MONK1"] = {
			["IconTexturePath"] = 608951,
			["PerCharacterOptions"] = {
				["Korym-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "00fe97",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Brewmaster",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "00be71",
		},
		["\"MrRobot\":EVOKER1"] = {
			["IconTexturePath"] = 4511811,
			["PerCharacterOptions"] = {
			},
			["Color"] = "8cc2b7",
			["LocalizedName"] = "Evoker: Devastation",
			["ClassID"] = 13,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["UnenchantedColor"] = "699189",
			["SpecID"] = 1,
		},
		["\"MrRobot\":DEMONHUNTER1"] = {
			["IconTexturePath"] = 1247264,
			["PerCharacterOptions"] = {
				["Koryxd-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a22fc8",
			["ClassID"] = 12,
			["LocalizedName"] = "Demon Hunter: Havoc",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "792396",
		},
		["\"MrRobot\":DRUID4"] = {
			["IconTexturePath"] = 136041,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Restoration",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 4,
			["UnenchantedColor"] = "be5c06",
		},
		["\"MrRobot\":EVOKER2"] = {
			["IconTexturePath"] = 4511812,
			["PerCharacterOptions"] = {
			},
			["Color"] = "8cc2b7",
			["LocalizedName"] = "Evoker: Preservation",
			["ClassID"] = 13,
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["UnenchantedColor"] = "699189",
			["SpecID"] = 2,
		},
		["\"MrRobot\":WARRIOR3"] = {
			["IconTexturePath"] = 132341,
			["PerCharacterOptions"] = {
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Protection",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "937351",
		},
		["\"MrRobot\":ROGUE3"] = {
			["IconTexturePath"] = 132320,
			["PerCharacterOptions"] = {
				["Seloniax-Ravencrest"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fef367",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Subtlety",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "beb64d",
		},
		["\"MrRobot\":DRUID1"] = {
			["IconTexturePath"] = 136096,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Balance",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "be5c06",
		},
		["\"MrRobot\":PALADIN1"] = {
			["IconTexturePath"] = 135920,
			["PerCharacterOptions"] = {
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Holy",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "b6688a",
		},
		["\"MrRobot\":DEATHKNIGHT1"] = {
			["IconTexturePath"] = 135770,
			["PerCharacterOptions"] = {
				["Vonshala-Defias Brotherhood"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Blood",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "bf3950",
		},
		["Seloniaa - Balance - Patchwerk (Raidbots)"] = {
			["IconTexturePath"] = 136096,
			["Values"] = {
				["IsOffHand"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 1.72,
				["HasteRating"] = 2.49,
				["MasteryRating"] = 2.44,
				["IsCrossbow"] = -1000000,
				["IsGun"] = -1000000,
				["Is2HAxe"] = -1000000,
				["IsThrown"] = -1000000,
				["IsBow"] = -1000000,
				["IsMail"] = -1000000,
				["IsPlate"] = -1000000,
				["IsWand"] = -1000000,
				["IsShield"] = -1000000,
				["Intellect"] = 4.07,
				["Versatility"] = 1.83,
				["Is2HSword"] = -1000000,
				["IsAxe"] = -1000000,
				["IsSword"] = -1000000,
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 1,
			["PerCharacterOptions"] = {
				["Seloniaa-Ravencrest"] = {
					["Visible"] = true,
				},
			},
		},
		["\"MrRobot\":HUNTER1"] = {
			["IconTexturePath"] = 461112,
			["PerCharacterOptions"] = {
			},
			["Color"] = "a9d271",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Beast Mastery",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "7e9d54",
		},
		["\"MrRobot\":DEMONHUNTER2"] = {
			["IconTexturePath"] = 1247265,
			["PerCharacterOptions"] = {
				["Koryxd-Frostwolf"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a22fc8",
			["ClassID"] = 12,
			["LocalizedName"] = "Demon Hunter: Vengeance",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "792396",
		},
		["\"MrRobot\":PALADIN2"] = {
			["IconTexturePath"] = 236264,
			["PerCharacterOptions"] = {
				["Anhædra-Outland"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Protection",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "b6688a",
		},
		["\"MrRobot\":WARRIOR1"] = {
			["IconTexturePath"] = 132355,
			["PerCharacterOptions"] = {
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Arms",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "937351",
		},
		["\"MrRobot\":WARLOCK2"] = {
			["IconTexturePath"] = 136172,
			["PerCharacterOptions"] = {
			},
			["Color"] = "8687ed",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Demonology",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "6465b1",
		},
		["Koryx - Unholy - Patchwerk (Raidbots)"] = {
			["IconTexturePath"] = 135775,
			["PerCharacterOptions"] = {
				["Koryx-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 3,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsFist"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 3.43,
				["IsStaff"] = -1000000,
				["HasteRating"] = 3.12,
				["MasteryRating"] = 3.29,
				["Versatility"] = 3.55,
				["IsThrown"] = -1000000,
				["IsFrill"] = -1000000,
				["Dps"] = 29.91,
				["Strength"] = 5.93,
				["IsDagger"] = -1000000,
				["IsCrossbow"] = -1000000,
				["IsGun"] = -1000000,
				["IsShield"] = -1000000,
				["IsBow"] = -1000000,
			},
		},
		["\"MrRobot\":SHAMAN3"] = {
			["IconTexturePath"] = 136052,
			["PerCharacterOptions"] = {
				["Zappyboyo-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "006fdc",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Restoration",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "0053a5",
		},
		["\"MrRobot\":DRUID2"] = {
			["IconTexturePath"] = 132115,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Feral",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "be5c06",
		},
		["Seloniax - Subtlety - Patchwerk (Raidbots)"] = {
			["IconTexturePath"] = 132320,
			["PerCharacterOptions"] = {
				["Seloniax-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fef367",
			["ClassID"] = 4,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 3,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsFist"] = -1000000,
				["Is2HMace"] = -1000000,
				["IsMace"] = -1000000,
				["CritRating"] = 2.51,
				["IsStaff"] = -1000000,
				["Agility"] = 5.32,
				["HasteRating"] = 2.11,
				["MasteryRating"] = 2.08,
				["IsCrossbow"] = -1000000,
				["IsPolearm"] = -1000000,
				["IsGun"] = -1000000,
				["IsFrill"] = -1000000,
				["Is2HAxe"] = -1000000,
				["IsBow"] = -1000000,
				["Dps"] = 28.44,
				["IsMail"] = -1000000,
				["IsSword"] = -1000000,
				["IsWarglaive"] = -1000000,
				["OffHandDps"] = 1.19,
				["Versatility"] = 2.63,
				["IsPlate"] = -1000000,
				["Is2HSword"] = -1000000,
				["IsShield"] = -1000000,
				["IsAxe"] = -1000000,
			},
		},
		["Felwinter - Arms - Dungeon Slice (BETA) (Raidbots)"] = {
			["IconTexturePath"] = 132355,
			["PerCharacterOptions"] = {
				["Felwinter-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 1,
			["Values"] = {
				["IsWand"] = -1000000,
				["IsFrill"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 4.17,
				["Dps"] = 36.14,
				["Strength"] = 6.8,
				["HasteRating"] = 3.98,
				["MasteryRating"] = 3.4,
				["Versatility"] = 3.77,
				["IsCrossbow"] = -1000000,
				["IsBow"] = -1000000,
				["IsGun"] = -1000000,
			},
		},
		["\"MrRobot\":ROGUE1"] = {
			["IconTexturePath"] = 236270,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fef367",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Assassination",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "beb64d",
		},
		["\"MrRobot\":HUNTER2"] = {
			["IconTexturePath"] = 236179,
			["PerCharacterOptions"] = {
				["Aliethea-Defias Brotherhood"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a9d271",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Marksmanship",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "7e9d54",
		},
		["\"MrRobot\":WARRIOR2"] = {
			["IconTexturePath"] = 132347,
			["PerCharacterOptions"] = {
			},
			["Color"] = "c59a6c",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Fury",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "937351",
		},
		["\"MrRobot\":MONK2"] = {
			["IconTexturePath"] = 608952,
			["PerCharacterOptions"] = {
			},
			["Color"] = "00fe97",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Mistweaver",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "00be71",
		},
		["\"MrRobot\":DEATHKNIGHT2"] = {
			["IconTexturePath"] = 135773,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Frost",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "bf3950",
		},
		["\"MrRobot\":PALADIN3"] = {
			["IconTexturePath"] = 135873,
			["PerCharacterOptions"] = {
				["Injured-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "f38bb9",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Retribution",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "b6688a",
		},
		["\"MrRobot\":MAGE1"] = {
			["IconTexturePath"] = 135932,
			["PerCharacterOptions"] = {
			},
			["Color"] = "3ec6ea",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Arcane",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "2e94af",
		},
		["\"MrRobot\":DEATHKNIGHT3"] = {
			["IconTexturePath"] = 135775,
			["PerCharacterOptions"] = {
				["Selonia-Frostwolf"] = {
					["Visible"] = true,
				},
				["Anhaedra-Lightbringer"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Unholy",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "bf3950",
		},
		["\"MrRobot\":DRUID3"] = {
			["IconTexturePath"] = 132276,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fe7b09",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Guardian",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "be5c06",
		},
		["\"MrRobot\":PRIEST2"] = {
			["IconTexturePath"] = 237542,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fefefe",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Holy",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "bebebe",
		},
		["\"MrRobot\":SHAMAN2"] = {
			["IconTexturePath"] = 237581,
			["PerCharacterOptions"] = {
				["Amarya-Twisting Nether"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "006fdc",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Enhancement",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "0053a5",
		},
		["\"MrRobot\":MONK3"] = {
			["IconTexturePath"] = 608953,
			["PerCharacterOptions"] = {
				["Elanoir-Defias Brotherhood"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "00fe97",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Windwalker",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "00be71",
		},
	},
	["LastVersion"] = 2.0801,
	["ButtonPosition"] = 2,
	["ShowLootUpgradeAdvisor"] = true,
	["ShowQuestUpgradeAdvisor"] = true,
	["ShowSpecIcons"] = true,
	["IgnoreGemsWhileLeveling"] = true,
}
